window.Linggong.agency = {
  render(view) {
    const pages = { home: agencyHome, talents: talentLibrary, tasks: agencyTasks, trade: agencyTrade, profile: agencyProfile, detail: agencyTaskDetail, publish: publishTask };
    return (pages[view] || agencyHome)();
  }
};
function agencyHome(){return `<section class="m-page agency-page"><div class="m-hero agency-hero"><div class="m-brand">灵工云 <span>· 机构版</span></div><button class="m-icon">•••</button><h1>让达人合作，<br>更高效、更可控</h1><p>连接优质服务者，统一管理任务与结算</p><button class="m-login" onclick="Linggong.go('publish')">发布合作需求　→</button></div><div class="m-shortcuts"><button onclick="Linggong.go('talents')"><i>♧</i>达人库</button><button onclick="Linggong.go('tasks')"><i>▣</i>任务管理</button><button onclick="Linggong.go('trade')"><i>￥</i>交易管理</button></div><div class="m-notice">🔊　平台已上线 30 万+认证服务者，立即匹配合作人选</div><section class="m-section"><div class="m-title"><b>优质达人</b><button onclick="Linggong.go('talents')">查看达人库　›</button></div><div class="agency-cats"><span>美妆个护<small>4.3 万达人</small></span><span>时尚穿搭<small>2.1 万达人</small></span><span>精品美食<small>3.3 万达人</small></span><span>母婴亲子<small>1.8 万达人</small></span><span>运动健康<small>1.8 万达人</small></span><span>宠物生活<small>6 千达人</small></span></div></section><section class="m-section"><div class="m-title"><b>进行中的合作</b><button onclick="Linggong.go('tasks')">全部　›</button></div>${agencyTaskCards().slice(0,2).join('')}</section></section>`}
function talentLibrary(){const rows=[['一条小团团OvO','美妆个护','小红书 · 148W粉丝'],['陈墨','时尚穿搭','抖音 · 32.3W粉丝'],['阿禾的食光','精品美食','视频号 · 54W粉丝']];return `<section class="m-page"><div class="m-bluebar"><b>达人广场</b><span>•••</span></div><div class="m-platforms"><b>小红书</b><span>抖音</span><span>视频号</span></div><div class="m-filter"><button>内容领域⌄</button><button>粉丝量级⌄</button><button>综合排序⌄</button></div><div class="m-banner"><strong>还没找到合适的达人？</strong><small>发布合作需求，平台为你智能匹配</small><button onclick="Linggong.go('publish')">立即发布</button></div><section class="m-section compact">${rows.map((p,i)=>`<article class="person-card"><div class="avatar a${i}">${p[0].slice(0,1)}</div><div><b>${p[0]} <em>已认证</em></b><p>${p[1]}</p><small>${p[2]}</small></div><button onclick="Linggong.notice('已加入合作候选')">合作</button></article>`).join('')}</section></section>`}
function agencyTasks(){return `<section class="m-page"><div class="m-bluebar"><b>任务管理</b><span>•••</span></div><div class="m-tabs"><button class="active">全部</button><button>招募中</button><button>执行中</button></div><div class="m-filter"><button>任务类型⌄</button><button>发布时间⌄</button><button>任务状态⌄</button></div><section class="m-section compact">${agencyTaskCards().join('')}</section><button class="m-fab" onclick="Linggong.go('publish')">＋</button></section>`}
function agencyTaskCards(){return [`<article class="task-card" onclick="Linggong.go('detail')"><div><b>夏季护肤新品种草</b><em>招募中</em><p>小红书图文种草，面向美妆个护达人</p><small>预算 ¥30,000　·　已报名 12 人</small></div><strong>¥30K<small>预算</small></strong></article>`,`<article class="task-card" onclick="Linggong.go('detail')"><div><b>品牌快闪活动传播</b><em>执行中</em><p>线下活动探店与短视频传播合作</p><small>上海 · 已合作 8 人</small></div><strong>¥18K<small>预算</small></strong></article>`,`<article class="task-card" onclick="Linggong.go('detail')"><div><b>秋季服饰穿搭推广</b><em>待确认</em><p>抖音短视频创作及直播口播合作</p><small>计划 8 月上线</small></div><strong>¥45K<small>预算</small></strong></article>`]}
function agencyTrade(){return `<section class="m-page"><div class="m-bluebar"><b>交易管理</b><span>•••</span></div><div class="m-balance"><small>本月合作预算（元）</small><b>86,000.00</b><button onclick="Linggong.go('tasks')">查看任务</button></div><div class="m-stats"><span><b>18</b>合作订单</span><span><b>6</b>待结算</span><span><b>3</b>待开票</span></div><section class="m-section compact"><div class="m-title"><b>结算记录</b><button>全部　›</button></div>${[['夏季护肤新品种草','待结算','¥12,000'],['活动传播第一期','已支付','¥8,600'],['达人服务费','审核中','¥3,200']].map(x=>`<div class="trade-row"><div class="trade-icon">￥</div><div><b>${x[0]}</b><small>${x[1]}　2026-07-29</small></div><strong>${x[2]}</strong></div>`).join('')}</section></section>`}
function agencyProfile(){return `<section class="m-page profile-page"><div class="profile-head"><button class="m-icon">⚙</button><div class="profile-user"><div class="avatar a1">星</div><div><b>星澜品牌机构</b><small>企业认证已完成　›</small></div></div><div class="profile-data"><span><b>36</b>发布任务</span><span><b>128</b>合作达人</span><span><b>98%</b>履约率</span></div></div><section class="m-section profile-menu"><div class="m-title"><b>机构服务</b></div><button onclick="Linggong.go('tasks')">任务管理 <span>›</span></button><button onclick="Linggong.go('talents')">我的达人库 <span>›</span></button><button onclick="Linggong.go('trade')">交易与发票 <span>›</span></button><div class="m-title lower"><b>机构设置</b></div><button>企业认证 <span>已认证　›</span></button><button>成员与权限 <span>›</span></button></section></section>`}
function agencyTaskDetail(){return `<section class="m-page"><div class="m-detail-top"><button class="m-back" onclick="Linggong.go('tasks')">‹</button><b>任务详情</b><span>•••</span></div><section class="detail-content"><div class="detail-state">招募中</div><h2>夏季护肤新品种草</h2><p>小红书图文种草，面向美妆个护类认证达人</p><div class="detail-money">¥30,000 <small>合作预算</small></div><div class="detail-info"><span>合作形式<b>图文种草</b></span><span>计划周期<b>15 天</b></span><span>报名人数<b>12 人</b></span></div><h3>合作要求</h3><p>粉丝量级 1 万以上，内容风格与品牌调性匹配；发布前须完成内容审核。</p><h3>候选达人</h3><p>已有 12 位达人报名，建议优先查看数据与报价。</p></section><div class="m-bottom-action"><button onclick="Linggong.go('talents')">查看候选达人</button></div></section>`}
function publishTask(){return `<section class="m-page"><div class="m-detail-top"><button class="m-back" onclick="Linggong.go('home')">‹</button><b>发布合作需求</b><span></span></div><section class="m-section accept"><h3>新建达人合作任务</h3><p>完善需求后，平台将为你推荐合适达人。</p><label>任务名称<input value="夏季护肤新品种草"></label><label>合作预算<input value="30,000"></label><label>任务说明<textarea placeholder="填写内容平台、合作形式与达人要求"></textarea></label><button class="m-main" onclick="Linggong.notice('任务发布成功，正在匹配达人');Linggong.go('tasks')">发布任务</button></section></section>`}
