window.Linggong.ui = {
  header: (title, description, action="") => `<div class="heading"><div><h1>${title}</h1><p>${description}</p></div>${action}</div>`,
  status: (name) => `<span class="state state-${Linggong.status[name] || "processing"}">${name}</span>`,
  sampleRows: (rows, count=20) => { const companies=["北京启辰数字科技有限公司","上海远屿品牌管理有限公司","广州知行营销服务有限公司","深圳星火创意科技有限公司","杭州云帆文化传媒有限公司","成都青柠互动科技有限公司","武汉悦行企业服务有限公司","南京拾光品牌管理有限公司","苏州澄明信息技术有限公司","厦门海岸线文化传播有限公司","重庆新页数字科技有限公司","长沙橙子营销策划有限公司","天津北辰企业管理有限公司","郑州优途网络科技有限公司","青岛澜海品牌咨询有限公司","合肥远见人力资源有限公司","宁波星河商务服务有限公司","福州山海内容科技有限公司","西安长安创意设计有限公司","昆明春城数字营销有限公司"]; return Array.from({length:count}, (_,i)=>{const copy=[...rows[i%rows.length]], companyIndex=copy.findIndex(x=>String(x).includes("公司")), codeIndex=copy.findIndex(x=>/^[A-Z]{2,}\d/.test(String(x))); if(companyIndex>-1)copy[companyIndex]=companies[i%companies.length]; if(codeIndex>-1)copy[codeIndex]=`${copy[codeIndex]}-${String(i+1).padStart(2,"0")}`; return copy}) },
  pageRows: (key, rows) => { const p=Linggong.state.pagers?.[key]||{page:1,size:10}, start=(p.page-1)*p.size; return rows.slice(start,start+p.size); },
  pagination: (key,total) => { const p=Linggong.state.pagers?.[key]||{page:1,size:10}, pages=Math.max(1,Math.ceil(total/p.size)); return `<div class="pagination"><span>共 ${total} 条</span><select onchange="Linggong.setPageSize('${key}',this.value)">${[10,20,40,50].map(x=>`<option value="${x}" ${p.size===x?"selected":""}>${x} 条/页</option>`).join("")}</select><button ${p.page===1?"disabled":""} onclick="Linggong.setPage('${key}',${p.page-1})">‹</button>${Array.from({length:pages},(_,i)=>`<button class="${p.page===i+1?"active":""}" onclick="Linggong.setPage('${key}',${i+1})">${i+1}</button>`).join("")}<button ${p.page===pages?"disabled":""} onclick="Linggong.setPage('${key}',${p.page+1})">›</button></div>`; },
  table: (rows, kind="任务", key=kind) => { const all=Linggong.ui.sampleRows(rows), pageRows=Linggong.ui.pageRows(key,all); return `<div class="table"><table><thead><tr><th>${kind}名称</th><th>编号</th><th>状态</th><th>金额 / 时间</th><th>操作</th></tr></thead><tbody>${pageRows.map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${Linggong.ui.status(r[2])}</td><td>${r[3]}</td><td><button class="plain" onclick="Linggong.go('detail')">查看详情</button></td></tr>`).join("")}</tbody></table></div>${Linggong.ui.pagination(key,all.length)}`; },
  list: (title, desc, rows, kind, action, target) => `<p class="crumb">首页 / ${title}</p>${Linggong.ui.header(title, desc, `<button class="primary" onclick="Linggong.go('${target}')">${action}</button>`)}<div class="tabs"><button class="active">全部</button><button>待审核</button><button>进行中</button><button>已完成</button></div>${Linggong.ui.table(rows,kind,title)}`,
  form: (title, next) => `<p class="crumb">首页 / ${title}</p><form class="form" onsubmit="event.preventDefault();Linggong.notice('提交成功，已进入下一环节');Linggong.go('${next}')"><h2>${title}</h2><div class="form-grid"><label>名称<input value="${title==='发布任务'?'活动运营专员':'杭州星澜科技有限公司'}"></label><label>业务类型<select><option>现代服务</option><option>运营推广</option></select></label><label>金额 / 周期<input value="¥ 30,000"></label><label>联系人<input value="138 0000 2026"></label><label class="wide">说明<textarea>请填写相关业务信息与协作要求。</textarea></label></div><div class="foot"><button class="primary">提交并继续</button></div></form>`,
  detail: (title, status, action="") => `<p class="crumb">首页 / 详情</p>${Linggong.ui.header(title, Linggong.ui.status(status), action)}<section class="card"><h2>基本信息</h2><div class="row"><span>业务编号</span><b>RW20260721001</b></div><div class="row"><span>服务报酬</span><b>¥30,000</b></div><div class="row"><span>执行周期</span><b>2026-08-01 至 2026-08-31</b></div><div class="row"><span>当前进度</span><b>68%</b></div></section>`
};
